version: '3'

services:
  service-news-aggregator:
    container_name: service-news-aggregator
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
    command: npm run dev -- --host